name: Tests
on: [push, pull_request]
jobs:
  ubuntu_test:
    name: Ubuntu tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Lints
        run: |
          ./testing/run_travis_lints.sh
      - name: Tests
        run: |
          ./testing/run_travis_tests.sh
